Refactored getCurrentUser.js
noblox/noblox.js pull request #579
Opened 2022-05-30 09:35 UTC by nikos467

Made the export function easier  to read

2022-06-10 13:25 UTC, Neztore requested changes
Please edit your PR to set the internally stored token in jar

2022-06-10 13:25 UTC, Neztore commented on lib/user/setCookie.js
> +    const res = await getCurrentUser({ jar: { session: args.cookie } })
Could `return await getCurrentUser(...);` to remove an unnecessary line and variable.

2022-06-10 13:25 UTC, Neztore commented on lib/user/setCookie.js
> +    const res = await getCurrentUser({ jar: { session: args.cookie } })
Or, a better solution would be to match the original behaviour and actually set the session token following validation!

Please test your PRs. Reading your code, if validate is enabled the internally stored cookie will never be updated.

2022-07-04 13:23 UTC, Chosey98 commented
Matter of fact I just reviewed and pushed the changes @Neztore requested to @nikos467 branch and waiting his approval to merge

2022-11-02 12:34 UTC, Neztore commented
No activity and fixed elsewhere

2022-11-02 12:34 UTC, closed without merging