Add getGameSorts and getGameList
noblox/noblox.js pull request #651
Opened 2022-12-14 08:45 UTC by alexop1000

This adds support for getting the different sorts and the games in them.

2023-04-27 23:50 UTC, alanbixby commented on lib/game/getGameList.js
> +    .then((body) => {
We would want this to be using the pagination logic; currently this would only return the first page.

2023-04-28 00:15 UTC, alanbixby requested changes

2023-04-28 00:15 UTC, alanbixby commented on lib/game/getGameSorts.js
> + * @param {string|number} gameSortsContext - The sort context to get.
Would prefer defined enums here; I know its tedious given the modern documentation but they are

"GamesDefaultSorts",
"GamesAllSorts",
"HomeSorts",
"ChatSorts"

hilariously, the "updated" docs, list 0 - 7 but only 0 - 3 work without throwing an HTTP 500; thanks Roblox

2023-04-28 06:21 UTC, alexop1000 commented
That's true, but it's been 4 months and I'm not fixing that now xD. But yeah the Roblox docs is very misleading. They also still use OpenAPI 2.0 instead of 3.0

2023-08-07 19:37 UTC, Neztore commented
Author has no plans to bring this to a mergable state, closing. Feel free to pick it up if you need these functions.

2023-08-07 19:37 UTC, closed without merging