Check for existence of shout before parsing dates
noblox/noblox.js pull request #685
Opened 2023-03-15 22:07 UTC by Wolftallemo

The `shout` property is null for groups that have never set a shout.

2023-03-15 22:42 UTC, suufi approved these changes

2023-03-15 22:42 UTC, suufi requested changes
Typings should be `shout?: GroupShout`

2023-03-15 22:46 UTC, suufi approved these changes

2023-04-05 08:35 UTC, Chosey98 commented
@suufi I believe this is ready to be merged as this is an important commit blocking an important method. If any changes else are requested can you let me know as I need this commit pushed asap so I would like to help.

2023-04-06 07:44 UTC, merged