add getUserFavoriteGames
noblox/noblox.js pull request #694
Opened 2023-04-05 16:07 UTC by AbdullahalyDev

2023-04-06 07:48 UTC, suufi requested changes

2023-04-06 07:48 UTC, suufi commented on lib/accountinformation/getUserFavoriteGames.js
> + * @category AccountInformation
Not the right category

2023-04-06 07:48 UTC, suufi commented on lib/accountinformation/getUserFavoriteGames.js
> +function getUserFavoriteGames (userId, limit) {
missing multiple parameters specified by the endpoint

see: https://games.roblox.com/docs/index.html

2023-04-06 07:48 UTC, suufi commented on lib/accountinformation/getUserFavoriteGames.js
> +  return getUserFavoriteGames(userId, accessFilter, limit, cursor, sortOrder)
should be handled with getPageResults

2023-04-06 07:48 UTC, suufi commented on test/accountinformation.test.js
> +        data: expect.toBeOneOf([expect.any(Object), null]),
needs to be more specific than this

2023-04-06 07:48 UTC, suufi commented on test/accountinformation.test.js
> +  it ('getUserFavoriteGame() return a player\' favorite games', () => {
player's*

2023-04-06 07:48 UTC, suufi commented on test/accountinformation.test.js
> +    return await expect(getUserFavoriteGames()).rejects.toThrow()
you should actually pass an invalid user id here

2023-04-06 07:48 UTC, suufi commented on typings/index.d.ts
> +    /**
not the right category, should be under games

2023-04-06 07:48 UTC, suufi commented on typings/index.d.ts
> +    type UserFavoriteGames = {
interface*

2023-04-23 14:37 UTC, Neztore requested changes
Looks good! A few things to fix with the docs though.

2023-04-23 14:37 UTC, Neztore commented on lib/games/getUserFavoriteGames.js
> + * @param {number} cursor - The  number of results per request.
Cursor parameter description

2023-04-23 14:37 UTC, Neztore commented on lib/games/getUserFavoriteGames.js
> + * @param {number} accessFilter - The  number of results per request.
Access filter description

2023-04-23 14:37 UTC, Neztore commented on lib/games/getUserFavoriteGames.js
> + * @param {number} sortOrder - The  number of results per request.
sortOrder description

2023-06-18 01:12 UTC, AbdullahalyDev commented
.

2023-07-20 21:44 UTC, closed without merging