Fix addDeveloperProduct not returning a product id
noblox/noblox.js pull request #751
Opened 2023-08-28 15:41 UTC by iamEvanYT

When using the new api, it returns a completely different id. I can then use that id to grab the real product id using a GET api.

2023-11-20 10:28 UTC, Neztore requested changes
Please make sure tests and `npm run lint` pass. Once CI passes I will review.

Cheers.

2023-11-22 23:49 UTC, iamEvanYT commented
@Neztore there we go.

2023-12-29 23:39 UTC, Ratzifutzi commented
When will the changes be fixed?

2024-01-12 12:40 UTC, Neztore approved these changes

2024-02-14 15:31 UTC, merged