Fixed case sensitivity in getIdFromUsername.js
noblox/noblox.js pull request #782
Opened 2024-03-05 21:37 UTC by MilesSRC

Fixed an issue in noblox.js where the API incorrectly handles usernames that are not in lowercase. When getIdFromUsername() receives a username like "ROBLOX," the API responds with "roblox" in the requestedUsername field. Previously, noblox.js did not account for this case-insensitive behavior, leading to issues in users' code. This has now been addressed.

2024-03-07 03:21 UTC, Jetfeliks746 commented
It still isn't working for me. I tried both uppercase and lowercase but the getIdFromUsername still return null.

2024-03-07 04:41 UTC, commonly-ts commented
I can confirm that this fix works. Tested it on a bot with a user on the Discord who's username didn't work, but after adding this fix to my code, it worked.

2024-03-07 04:42 UTC, commonly-ts approved these changes
I can confirm that this fix works. Tested it on a bot with a user on the Discord who's username didn't work, but after adding this fix to my code, it worked.

2024-03-07 04:45 UTC, Jetfeliks746 commented
> It still isn't working for me. I tried both uppercase and lowercase but the getIdFromUsername still return null.

Issue has been fixed!

edited line 38 in the noblox.js Node Modules to this:
return data.find((result) => result.requestedUsername === username.toLowerCase())

2024-03-09 08:26 UTC, policetonyR requested changes
I was able to resolve this by changing line 50 instead of doing your method.

`return cache.wrap('IDFromName', usernames, function () {`

2024-03-10 05:07 UTC, closed without merging

2024-03-10 05:07 UTC, MilesSRC commented
Closed PR, ROBLOX has fixed the issue.