Fix getPlayerInfo again
noblox/noblox.js pull request #850
Opened 2024-12-13 22:06 UTC by Regalijan

There are three issues which this solves

- The returned response/value object was never an array to begin with and that finally stopped working at some point that I can't figure out (which is now made moot by the fact that we no longer return response objects since #840)
- We were accessing the `.body` property on the body itself since that change and I forgot to change that beforehand.
- We would throw `User does not exist` regardless of what the true error was, now the error(s) is actually logged.

2024-12-13 22:40 UTC, Neztore requested changes
This code isn't usable at present -we need to find the source of the 429s. If we need to drop functionality so be it

2025-02-13 00:03 UTC, alanbixby commented
Is `getUsernameHistory` the source of the 429's - I was under the impression it was the follower endpoints? 

Arguably, we may want to deprecate this function altogether, and add a `console.warn` if it 429's pointing to the new split off methods in #840 and then stage a new release.

2025-02-13 00:05 UTC, Regalijan commented
Yeah the request rate is 1/2 per minute on a clean residential ip.

This arguably should be deprecates but that wasn't brought up when this was first opened.

2025-02-13 00:53 UTC, alanbixby reviewed
![image](https://github.com/user-attachments/assets/4962979a-4c28-41fe-a6b6-6ffb1356aa77)

Receiving rate limits on follower endpoints on a residential IP within ~15 reqs/min - going to deprecate this and trigger a banner pointing to the individualized endpoints

![image](https://github.com/user-attachments/assets/c7b03235-00f7-4308-8b79-aeb9b6f84163)

2025-02-13 00:56 UTC, alanbixby approved these changes

2025-02-13 01:07 UTC, merged